exclude: |
    (?x)^(
        python/.*/auto_\w+/.*.py|
        external/.*|
        tests/testdata/script_with_error.py
    )$
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    # if adding directory handled by clang-format
    # you need to adapt prepare_commit and verify_indentation scripts accordingly
    hooks:
    - id: clang-format
      types_or: [c++, c, c#]
      exclude: |
        (?x)^(
            src/core/.*|
            tests/code_layout/sipify/sipifyheader.h
        )$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: prepare_commit
        name: prepare_commit
        entry: ./scripts/prepare_commit.sh
        language: system
        always_run: true
        pass_filenames: false

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
