exclude: |
    (?x)^(
        python/.*/auto_\w+/.*.py|
        external/.*|
        tests/testdata/script_with_error.py
    )$
fail_fast: false

repos:
  - repo: local
    hooks:
      - id: banned_keywords
        name: banned_keywords
        entry: ./scripts/pre_commit/prepare_commit_banned_keywords.sh
        language: system
        always_run: true
        pass_filenames: true

  - repo: local
    hooks:
      - id: class_names
        name: class_names
        entry: ./scripts/pre_commit/prepare_commit_class_names.sh
        language: system
        always_run: true
        pass_filenames: true

  - repo: local
    hooks:
      - id: spell_check
        name: spell_check
        entry: ./scripts/pre_commit/prepare_commit_spell_check.sh
        language: system
        always_run: true
        pass_filenames: true

  - repo: local
    hooks:
      - id: doxygen_test
        name: doxygen_test
        entry: ./scripts/pre_commit/prepare_commit_doxygen_test.sh
        language: system
        always_run: true
        pass_filenames: true


  - repo: local
    hooks:
      - id: code_fixup
        name: code_fixup
        entry: ./scripts/pre_commit/prepare_commit_code_fixup.sh
        language: system
        always_run: true
        pass_filenames: true

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: ./scripts/pre_commit/prepare_commit_shellcheck.sh
        language: system
        always_run: true
        pass_filenames: true

  - repo: local
    hooks:
      - id: prepare_commit
        name: prepare_commit
        entry: ./scripts/pre_commit/prepare_commit.sh
        language: system
        always_run: true
        pass_filenames: true

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    # if adding directory handled by clang-format
    # you need to adapt prepare_commit and verify_indentation scripts accordingly
    hooks:
    - id: clang-format
      types_or: [c++, c, c#]
      exclude: |
        (?x)^(
            src/core/.*
        )$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # MUST run last
  - repo: local
    hooks:
      - id: prepare_sip
        name: prepare_sip
        entry: ./scripts/pre_commit/prepare_commit_sip.sh
        language: system
        always_run: true
        pass_filenames: true
