version: '3'
services:
  postgres:
    image: kartoza/postgis:9.5-2.2
    environment:
      - ALLOW_IP_RANGE="172.18.0.0/16"

  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: <YourStrong!Passw0rd>

  qgis-deps:
    tty: true
    image: qgis/qgis3-build-deps:${DOCKER_TAG}
    volumes:
      - ${TRAVIS_BUILD_DIR}:/root/QGIS
      - $HOME/.ccache:/root/.ccache  # if changed, also change env var
    links:
      - postgres
      - mssql
    environment:
      - CCACHE_DIR=/root/.ccache
      - CTEST_BUILD_DIR=/root/QGIS
      - TRAVIS_BRANCH=${TRAVIS_BRANCH}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      - TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE}
      - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
      - TRAVIS_CONFIG=${TRAVIS_CONFIG}
      - TRAVIS=${TRAVIS}
      - TRAVIS_TIMESTAMP=${TRAVIS_TIMESTAMP}
      - QGIS_DISABLE_MESSAGE_HOOKS=1
      - QGIS_NO_OVERRIDE_IMPORT=1
