services:

  oracle:
    image: oslandia/oracle-slim-for-qgis:18.4.0-xe
    environment:
      - ORACLE_SID=XE
      - ORACLE_PWD=adminpass
      - ORACLE_PDB=ORCLPDBTEST
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - 1521:1521
    networks:
      - qgisnet

  qgis-deps:
    tty: true
    image: qgis3-build-deps-binary-image
    volumes:
      - ${QGIS_WORKSPACE}:/root/QGIS
    depends_on:
      - oracle
    env_file:
      - docker-variables.env
    environment:
      - LANG=C.UTF-8
      - LC_ALL=en_US.UTF-8
    networks:
      - qgisnet

networks:
  qgisnet:
    driver: bridge
