version: '3'
services:
  postgres:
    image: kartoza/postgis:9.5-2.2
    command: sh -c "echo \"host all all 172.18.0.0/16 md5\" >> /etc/postgresql/9.5/main/pg_hba.conf && /start-postgis.sh"

  qgis-deps:
    image: qgis/qgis3-build-deps:${DOCKER_TAG}
    volumes:
      - ${TRAVIS_BUILD_DIR}:/root/QGIS
      - $HOME/.ccache:/root/.ccache
    links:
      - postgres
    environment:
      - TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
      - TRAVIS_COMMIT_RANGE=${TRAVIS_COMMIT_RANGE}
      - TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
      - TRAVIS_CONFIG=${TRAVIS_CONFIG}
