name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: contains( join(github.event.pull_request.labels.*.name), 'backport')
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - name: Backport Bot
        uses: Gaurav0/backport@v1.0.24
        with:
          bot_username: qgis-bot
          bot_token: ddbdec32940df79f1adf2369b4b10f10b5a66f65
          bot_token_key: a1b2c3d47311f8e29e204f85a81b4df4a44e252c
          github_token: ${{ secrets.GITHUB_TOKEN }}
