name: MSYS2 MinGW-w64 Windows 64bit Build

on:
  push:
    branches:
      - master
      - release-**
      - queued_ltr_backports
    paths:
    - 'src/**'
    - 'external/**'
    - 'python/**'
    - 'tests/**'
    - 'ms-windows/**'
    - 'CMakeLists.txt'
    - '.github/workflows/mingw-w64-msys2.yml'
  pull_request:
  workflow_dispatch:

jobs:
  mingw-w64-msys2-build:
    name: MSYS2 MinGW-w64 Windows Build
    runs-on: windows-latest
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    QT_VERSION: [qt5, qt6]
    #    MSYSTEM: [UCRT64, CLANG64]
    env:
      CCACHE_DIR: build/ccache
    defaults:
      run:
        shell: msys2 {0}
    steps:

      - uses: actions/checkout@v4

      - name: Install core & build dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: base-devel
          pacboy: >-
            protobuf:p gdal:p libzip:p qca-qt5:p gsl:p exiv2:p hdf5:p libxml2:p netcdf:p opencl-icd:p
            pdal:p proj:p qt5-3d:p qt5-base:p qt5-declarative:p qt5-gamepad:p qt5-location:p
            qt5-serialport:p qt5-svg:p qtkeychain-qt5:p qtwebkit:p qscintilla-qt5:p qwt-qt5:p
            spatialindex:p cc:p cmake:p ninja:p opencl-clhpp:p qt5-tools:p python:p ccache:p
          update: true
          release: false

      - name: Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: build
          key: build-ccache-mingw64-msys2-${{Â github.event.pull_request.base.ref || github.ref_name }}
          restore-keys: |
            build-ccache-mingw64-msys2-master

      - name: Configure QGIS
        run: |
          CXXFLAGS="-DQWT_POLAR_VERSION=0x060200" \
          cmake \
            -G"Ninja" \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DPython_EXECUTABLE=${MINGW_PREFIX}/bin/python \
            -DWITH_3D=ON \
            -DWITH_PDAL=OFF \
            -DWITH_CUSTOM_WIDGETS=ON \
            -DWITH_QWTPOLAR=ON \
            -DQWTPOLAR_LIBRARY=${MINGW_PREFIX}/lib/libqwt-qt5.dll.a \
            -DQWTPOLAR_INCLUDE_DIR=${MINGW_PREFIX}/include/qwt-qt5 \
            -DWITH_INTERNAL_QWTPOLAR=OFF \
            -DWITH_BINDINGS=OFF \
            -DWITH_GRASS=OFF \
            -DWITH_DRACO=OFF \
            -DUSE_CCACHE=ON \
            -S . \
            -B build

      - name: Build QGIS
        run: |
          cmake --build build
          ccache -s

      - name: Save build cache for push only
        uses: actions/cache/save@v4
        if: ${{ github.event_name == 'push' }}
        with:
          path: build
          key: build-ccache-mingw64-msys2-${{ github.ref_name }}-${{ github.run_id }}
