name: Windows cross build with MXE

on: [push, pull_request]

#on:
# push:
#   branches-ignore:
#     - '**'
# pull_request:
#   branches-ignore:
#     - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cross build with MXE
      run: cd $GITHUB_WORKSPACE && ms-windows/mxe/build.sh
    - name: Rename artifact
      run: cd $GITHUB_WORKSPACE && mv qgis-mxe-release-*.zip qgis-mxe-release.zip
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: QGIS for Windows 64bit
        path: qgis-mxe-release.zip

