name: Run sipify

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release-*

jobs:
  sipify:
    if: github.repository == 'qgis/QGIS'
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Requirements
        run: pip install nose2 mock termcolor pyyaml

      - name: Get PR branch
        uses: alessbell/pull-request-comment-branch@ef3408c9757d05f89cb525036383033a313758a0 # v2.1.0
        if: ${{ github.event_name == 'issue_comment' }}
        id: comment-branch

      - uses: actions/checkout@v5

      - name: run sipify
        run: ./scripts/sipify_all.sh -m

      - name: commit
        run: |
          git config user.name qgis-bot
          git config user.email bot@qgis.org
          git add .
          git commit -m "auto sipify üç∫" || echo "nothing to commit"
          git push
